from typing import Dict, List, Any
from datetime import datetime
from pathlib import Path
from ..logging_utils import log_info, log_error, log_step
import json


class ReportGenerator:
    """Generates and exports OSINT findings as Markdown reports."""

    def __init__(self, export_dir: str = "reports"):
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(exist_ok=True)

    def generate_markdown(self, findings: Dict[str, Any], report_name: str = None) -> str:
        """Convert findings dictionary to Markdown report."""
        log_step("EXPORTING", "Generating Markdown report...")

        if report_name is None:
            report_name = f"osint_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        markdown = f"""# Parser RA Recon - OSINT Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Executive Summary

This report contains findings from the Parser RA Recon framework OSINT scan.

---

## Findings

"""

        for key, value in findings.items():
            markdown += f"\n### {key.upper()}\n\n"
            if isinstance(value, dict):
                markdown += self._dict_to_markdown(value)
            elif isinstance(value, list):
                markdown += "\n".join([f"- {item}" for item in value])
            else:
                markdown += str(value)
            markdown += "\n"

        markdown += "\n---\n\n*Report generated by Parser RA Recon*\n"

        return markdown

    def _dict_to_markdown(self, data: Dict, indent: int = 0) -> str:
        """Convert nested dictionary to Markdown."""
        md = ""
        for key, value in data.items():
            if isinstance(value, dict):
                md += f"{' ' * indent}- **{key}:**\n"
                md += self._dict_to_markdown(value, indent + 2)
            elif isinstance(value, list):
                md += f"{' ' * indent}- **{key}:**\n"
                for item in value:
                    md += f"{' ' * (indent + 2)}- {item}\n"
            else:
                md += f"{' ' * indent}- **{key}:** {value}\n"
        return md

    def save_report(self, markdown_content: str, filename: str = None) -> str:
        """Save Markdown report to file."""
        if filename is None:
            filename = f"osint_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"

        filepath = self.export_dir / filename
        log_info(f"Saving report to {filepath}")

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(markdown_content)
            log_step("COMPLETE", f"Report saved to {filepath}")
            return str(filepath)
        except Exception as e:
            log_error(f"Error saving report: {str(e)}")
            return None

    def generate_breach_summary(self, email_results: Dict) -> Dict:
        """Generate a safety rating card based on breach data."""
        log_step("RATING", "Generating safety score...")

        breaches_found = email_results.get("breaches_found", 0)
        breach_data = email_results.get("breach_data", [])

        # Simple risk scoring
        if breaches_found == 0:
            risk_level = "LOW"
            risk_score = 1
        elif breaches_found <= 2:
            risk_level = "MEDIUM"
            risk_score = 5
        elif breaches_found <= 5:
            risk_level = "HIGH"
            risk_score = 7
        else:
            risk_level = "CRITICAL"
            risk_score = 10

        summary = {
            "email": email_results.get("email"),
            "risk_level": risk_level,
            "risk_score": risk_score,
            "breaches_count": breaches_found,
            "breaches": breach_data,
            "recommendation": self._get_recommendation(risk_level),
        }

        log_info(f"Risk Level: {risk_level} ({risk_score}/10)")
        return summary

    def _get_recommendation(self, risk_level: str) -> str:
        """Get recommendation based on risk level."""
        recommendations = {
            "LOW": "Email appears safe. Continue monitoring regularly.",
            "MEDIUM": "Email exposed in few breaches. Consider password changes on affected services.",
            "HIGH": "Email exposed in multiple breaches. Immediate action recommended: change passwords, enable 2FA.",
            "CRITICAL": "Email critically compromised. Take immediate action across all accounts.",
        }
        return recommendations.get(risk_level, "Unknown risk level")
